### ISSUE TITLE
Umbrella: Image build and publishing

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-azure#270]
/kind feature

**Describe the solution you'd like**

Tomorrow:
- [ ] Figure out how to move to VHD / code changes @CecileRobertMichon 
- [x] Build sample test image using PR in image builder @CecileRobertMichon 

Short term:
- [ ] Figure out sponsorship / subscription @devigned
- [ ] Setup publisher in Azure Marketplace @devigned

**Comment by CecileRobertMichon** [comment]
VHD vs. managed image? https://github.com/MicrosoftDocs/azure-docs/issues/37716#issuecomment-536132262

**Comment by CecileRobertMichon** [comment]
WIP image-builder PR with pipeline to build a VHD with Packer (see previous commit for managed image in a shared image gallery): https://github.com/kubernetes-sigs/image-builder/pull/49/files

**Comment by CecileRobertMichon** [comment]
And here's an in-progress branch I started with some of the code changes required to build using a managed image in a share image gallery instead of a published image: https://github.com/kubernetes-sigs/cluster-api-provider-azure/compare/v1alpha2...CecileRobertMichon:valpha2-image-ref 

(disclaimer: I have not tested it)

**Comment by CecileRobertMichon** [comment]
fixed in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/302
