### ISSUE TITLE
AzureManagedCluster E2E: node pool tests

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-provider-azure#2855]
/kind feature
/area managedclusters

**Describe the solution you'd like**
E2E tests covering various node pool operations.

- [x] [AzureManagedCluster E2E: node pool Name CRUD](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2856)
- [ ] [AzureManagedCluster E2E: node pool Mode CRUD](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2857)
- [x] [AzureManagedCluster E2E: node pool Autoscaler CRUD](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2858)
- [x] [AzureManagedCluster E2E: node pool NodeLabels CRUD](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2859)
- [x] [AzureManagedCluster E2E: node pool Taints CRUD](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2860)

**Comment by dtzar** [comment]
/remove-lifecycle rotten
This is still valid, just not high enough priority to complete yet.

**Comment by jackfrancis** [comment]
Audited node pool tests, the only remaining item is updating "Mode" data for node pools.

**Comment by dtzar** [comment]
Closing this out as 4/5 are closed
