### ISSUE TITLE
Integrate azure-sdk-for-go v2

### ISSUE THREAD

**Issue by mboersma** [kubernetes-sigs/cluster-api-provider-azure#3409]
/kind feature

This is an umbrella issue to track the overall progress of converting services not covered by ASO (see #3402) to use Azure's SDK for Go version 2. 

```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3569
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3473
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3441
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3442
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3861
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3890
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3913
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3881
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3443
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3889
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3921
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3926
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3928
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3922
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3941
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3924
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3934
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3930
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3929
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3923
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3925
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3940
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3917
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3927
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3984
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3920
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3919
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3942
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3993
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3891
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3992
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3918
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3985
```

This list comes primarily from Azure/azure-service-operator#2237. This issue replaces #2670.

**Comment by mboersma** [comment]
I have a PR that converts NAT gateways and VNET peerings that I'll put out for review today.

**Comment by mboersma** [comment]
See https://github.com/Azure/azure-service-operator/issues/2237#issuecomment-1509372969 for discussion. This was based on a stale list and may be moot now.

**Comment by LochanRn** [comment]
Hi @mboersma @CecileRobertMichon 
I don't see a task for migration of the sdk to v2 for managedclusters. 
Any reason why ?
My team would like to help as we are looking forward for [this](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/2498) feature.

**Comment by mboersma** [comment]
@LochanRn sorry, I finally got around to adding tasks for converting managedcluster and agentpools (although really they're linked). I also opened a WIP PR here: #3857.

Until #3441 is fixed, I don't think any of these tasks can be done in parallel, but we're doing our best to get there and would love any reviews or advice or contributions you might have.

**Comment by LochanRn** [comment]
@mboersma Would love to contribute. So is there any task i can pick under this umbrella to help move things faster ?

**Comment by CecileRobertMichon** [comment]
@LochanRn managedclusters is our top priority for SDK v2 migration, PR is in progress #3794 

@mboersma is there a tracking issue we can add in here?

**Comment by mboersma** [comment]
I don't think there's any task here that's ready to work on yet, but hopefully that will change very soon, once one of the outstanding SDKv2 PRs is merged.

@CecileRobertMichon I'll convert the managedclusters item to an issue.

**Comment by dtzar** [comment]
@mboersma - which PR are we waiting to merge so LochanRn or others can help out potentially?

**Comment by mboersma** [comment]
@dtzar effectively we're waiting on #3857 to merge since that's when we'll have confidence in the `asyncpoller` framework and a couple of examples of how to use it.

**Comment by mboersma** [comment]
Now that the `asyncpoller` framework merged, I think the remaining tasks above could be done by other contributors, using #3882 as a model.

The managedclusters task is moving forward, and I'll promote the others to issues so others can claim them.

**Comment by mboersma** [comment]
The managedclusters/agentpools task finally looks to be about to merge. The remaining three tasks are up for grabs if anyone has bandwidth:
- #3889
- #3890
- #3891

You can use #3882 as a model.

**Comment by mboersma** [comment]
The current plan is: keep converting services to SDKv2 so we're not relying on the now-unsupported SDKv1. Then convert them over to ASO one-by-one.

**Comment by nawazkh** [comment]
I created https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3917 as a marker to update loadbalancer service.

**Comment by dtzar** [comment]
Going to close this so it shows as complete for 1.11 milestone release notes and such even though you will finish the one final `/test` code migration PR shortly after 1.11.
