### ISSUE TITLE
Improve unit test coverage in webhooks

### ISSUE THREAD

**Issue by willie-yao** [kubernetes-sigs/cluster-api-provider-azure#3648]
/kind cleanup

**What needs cleanup:**

This mega issue is meant to track individual issues for improving code coverage within CAPZ webhooks.

**Describe the solution you'd like**

```[tasklist]
### Tasks
- [ ] #3371
- [ ] #3652
- [ ] #3372
- [ ] #3374
- [ ] #3373
- [ ] #3429
- [ ] #3430
- [ ] #3431
- [ ] azuremanagedmachinepool_webhook.go
- [ ] #3432
- [ ] azuremachinepool_webhook.go
- [ ] azuremachinepoolmachine_webhook.go
```

Older parent issue: #3229
