### ISSUE TITLE
Node Prototyping Features

### ISSUE THREAD

**Issue by bennycortese** [kubernetes-sigs/cluster-api-provider-azure#3737]
/kind feature

This is an umbrella issue to track the overall progress of the effort described in the proposal to implement a node prototyping feature (#3624). It's currently a work-in-progress and will be updated as we identify and break down the work to be done.

Branch with examples of the work in the azuremachinepool reconciler: https://github.com/bennycortese/cluster-api-provider-azure/tree/cleanNodePrototypingBranch

Side repo with the code to currently just generate a new image for azuremachinepool use: https://github.com/bennycortese/bennytestgocapz

### Common Functionality
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3727
- [ ] Healthy AzureMachinePoolMachine determination
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3744
- [ ] Cleanup the node's unique identifiers
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3738
- [ ] Update the previous compute image gallery or construct a new one
- [ ] Delete the previous snapshot
- [ ] Changing the AzureMachinePoolMachine image to the new compute gallery image definition version
- [ ] Timestamping for last prototype taken
- [ ] Modifications to rolling update for this feature to disable it by default
```[tasklist]
### Tasks
```

**Comment by bennycortese** [comment]
To note here for any later collaborator on this, cleanup of the node's unique identifiers is much messier than initially anticipated. The biggest reason for this is because kubeadm leaves behind uniquely identifying information that has to be deleted before copying the image of the node. To solve this, kubeadm reset should be run as root user directly on the azuremachinepool itself and not on a pod acting on that azuremachinepool because pods will be unable to communicate with the node midway through the set of commands that kubeadm reset ends up running. This whole problem is largely because kubeadm reset is not atomic and runs commands consecutively rather than one giant command which queues up everything it wants to do at once. On top of all of this, CAPZ as a project should have no direct usage or reference to kubeadm reset because we don't require it to be present on the users' node, so this whole thing is a bigger issue than originally anticipated. Also if using the kubeadm reset method, be sure to also delete /run/kubeadm/kubeadm-join-config.yaml so that the token will get reset properly.

**Comment by bennycortese** [comment]
As far as snapshots go, you cannot shift the reference disk of a snapshot and update it to a new one. Thus, you must instantiate a new one and delete the previous one rather than updating a singular one over and over.

**Comment by bennycortese** [comment]
Also Compute Image Gallery Version Definitions are immutable in regard to the source disk, so you can't update the reference that they use. Thus, you must make a new Compute Image Gallery Version Definition and shift to that when you want to use a cached version as your new image.
