### ISSUE TITLE
Migrate Upstream tests to community infrastructure

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api-provider-azure#4976]
- CAPZ : [Click me for the list of CAPZ tests to be migrated](https://github.com/dtzar/test-infra/blob/nawaz-azure/hack/cluster-migration/cluster-api-provider-azure-job-migration-todo.md)
- Other repos 
  - image-builder : https://github.com/kubernetes-sigs/image-builder/issues/1508
  - azuredisk-csi-driver: https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/2410
  - azurefile-csi-driver: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1988
  - cloud-provider-azure : https://github.com/kubernetes-sigs/cloud-provider-azure/issues/6577
  - secrets-store-csi-driver: https://github.com/kubernetes-sigs/secrets-store-csi-driver/issues/1572
  - windows-testing: https://github.com/kubernetes-sigs/windows-testing/issues/453

------ 

### CAPZ Test migration history

- [x] [cluster-api-provider-azure-presubmits-main.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-azure/cluster-api-provider-azure-presubmits-main.yaml)

| Test Job Name                                                             | Migrate to use Workload Identity                                                         | Moved to community cluster | 
|--------------------------------------------------------------------------|-----------------------------------------------------------------| ------------------------------------------------------------------| 
| pull-cluster-api-provider-azure-e2e                                       | [PR: 32956](https://github.com/kubernetes/test-infra/pull/32956) | https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster` |
| pull-cluster-api-provider-azure-e2e-optional                              | [PR: 32956](https://github.com/kubernetes/test-infra/pull/32956)| https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster`  |
| pull-cluster-api-provider-azure-e2e-aks                                   | [PR: 32956](https://github.com/kubernetes/test-infra/pull/32956)|https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster`  |
| pull-cluster-api-provider-azure-capi-e2e                                  |   [PR: 32974](https://github.com/kubernetes/test-infra/pull/32974)  | https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster` |
| pull-cluster-api-provider-azure-conformance                               |  [ PR: 32974](https://github.com/kubernetes/test-infra/pull/32974) |https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster`  |
| pull-cluster-api-provider-azure-conformance-with-ci-artifacts             |  [PR: 32974](https://github.com/kubernetes/test-infra/pull/32974) |https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster`  |
| pull-cluster-api-provider-azure-conformance-ipv6-with-ci-artifacts        |   [PR: 32974](https://github.com/kubernetes/test-infra/pull/32974) | https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster` |
| pull-cluster-api-provider-azure-conformance-dual-stack-with-ci-artifacts  |  [PR: 32974](https://github.com/kubernetes/test-infra/pull/32974) |https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster`  |
| pull-cluster-api-provider-azure-windows-with-ci-artifacts                 |   [PR: 32974](https://github.com/kubernetes/test-infra/pull/32974) |https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster`  |
| pull-cluster-api-provider-azure-windows-containerd-upstream-with-ci-artifacts-serial-slow | [PR: 32974](https://github.com/kubernetes/test-infra/pull/32974) |https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster`  |
| pull-cluster-api-provider-azure-e2e-workload-upgrade                      | [PR: 32956](https://github.com/kubernetes/test-infra/pull/32956)| https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster` | 
| pull-cluster-api-provider-azure-apiversion-upgrade                        |   [PR: 32974](https://github.com/kubernetes/test-infra/pull/32974) |https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster`  |
| pull-cluster-api-provider-azure-ci-entrypoint                             |    [PR: 32974](https://github.com/kubernetes/test-infra/pull/32974)  |https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster`  |
| pull-cluster-api-provider-azure-conformance-custom-builds                 |  [PR: 32974](https://github.com/kubernetes/test-infra/pull/32974)  | https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster` |
| pull-cluster-api-provider-azure-windows-custom-builds                     |      [PR: 32974](https://github.com/kubernetes/test-infra/pull/32974)  | https://github.com/kubernetes/test-infra/pull/33030 running on `eks-prow-build-cluster` |
|pull-cluster-api-provider-azure-apidiff| WI creds not needed| running on `k8s-infra-prow-build`|
|pull-cluster-api-provider-azure-verify| WI creds not needed| running on `eks-prow-build-cluster`|
|pull-cluster-api-provider-azure-build| WI creds not needed|  running on `eks-prow-build-cluster`|
|pull-cluster-api-provider-azure-test| WI creds not needed| running on `eks-prow-build-cluster`|

- [x] [cluster-api-provider-azure-presubmits-release-v1beta1.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-azure/cluster-api-provider-azure-presubmits-release-v1beta1.yaml)

| Test Job Name                                                                  | Migrate to use Workload Identity | Moved to community cluster |
|-------------------------------------------------------------------------------|---------|---------|
| pull-cluster-api-provider-azure-e2e-v1beta1                                    |   https://github.com/kubernetes/test-infra/pull/32960      |        https://github.com/kubernetes/test-infra/pull/32960 running on `eks-prow-build-cluster` |
| pull-cluster-api-provider-azure-apiversion-upgrade-v1beta1                     |    https://github.com/kubernetes/test-infra/pull/32960     |    https://github.com/kubernetes/test-infra/pull/32960 running on `eks-prow-build-cluster`     |
| pull-cluster-api-provider-azure-e2e-optional-v1beta1                           |     https://github.com/kubernetes/test-infra/pull/32960    |    https://github.com/kubernetes/test-infra/pull/32960 running on `eks-prow-build-cluster`     |
| pull-cluster-api-provider-azure-e2e-aks-v1beta1                                |    https://github.com/kubernetes/test-infra/pull/32960     |    https://github.com/kubernetes/test-infra/pull/32960 running on `eks-prow-build-cluster`     |
| pull-cluster-api-provider-azure-capi-e2e-v1beta1                               |    https://github.com/kubernetes/test-infra/pull/32960     |   https://github.com/kubernetes/test-infra/pull/32960 running on `eks-prow-build-cluster`      |
| pull-cluster-api-provider-azure-conformance-v1beta1                            |    https://github.com/kubernetes/test-infra/pull/32960     |   https://github.com/kubernetes/test-infra/pull/32960 running on `eks-prow-build-cluster`      |
| pull-cluster-api-provider-azure-ci-entrypoint-v1beta1                          |    https://github.com/kubernetes/test-infra/pull/32960     |  https://github.com/kubernetes/test-infra/pull/32960 running on `eks-prow-build-cluster`       |
| pull-cluster-api-provider-azure-conformance-with-ci-artifacts-v1beta1          |   https://github.com/kubernetes/test-infra/pull/32960      |     https://github.com/kubernetes/test-infra/pull/32960 running on `eks-prow-build-cluster`    |
| pull-cluster-api-provider-azure-e2e-workload-upgrade-v1beta1                   |    https://github.com/kubernetes/test-infra/pull/32960     |     https://github.com/kubernetes/test-infra/pull/32960 running on `eks-prow-build-cluster`    |
| pull-cluster-api-provider-azure-test-v1beta1 | Does not use WI creds | running on `eks-prow-build-cluster` |
|pull-cluster-api-provider-azure-build-v1beta1 | Does not use WI creds | running on `eks-prow-build-cluster` |
|  pull-cluster-api-provider-azure-verify-v1beta1 | Does not use WI creds | running on `eks-prow-build-cluster` |
| pull-cluster-api-provider-azure-apidiff-v1beta1| Does not use WI creds | running on `k8s-infra-prow-build` |

- [x] [cluster-api-provider-azure-periodics-main.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-azure/cluster-api-provider-azure-periodics-main.yaml)

| Test Job Name                                                            | Migrate to use Workload Identity                                                         | Moved to community cluster |
|--------------------------------------------------------------------------|-----------------------------------------------------------------|-------------------|
| periodic-cluster-api-provider-azure-conformance-main                    | [PR: 32961](https://github.com/kubernetes/test-infra/pull/32961)| https://github.com/kubernetes/test-infra/pull/33013 Running at `k8s-infra-prow-build` |
| periodic-cluster-api-provider-azure-conformance-with-ci-artifacts-main   | [PR: 32961](https://github.com/kubernetes/test-infra/pull/32961)| https://github.com/kubernetes/test-infra/pull/33013 Running at `k8s-infra-prow-build` |
| periodic-cluster-api-provider-azure-capi-e2e-main                        | [PR: 32961](https://github.com/kubernetes/test-infra/pull/32961)| [PR: 33037](https://github.com/kubernetes/test-infra/pull/33037) Running on `eks-prow-build-cluster` |
| periodic-cluster-api-provider-azure-apiversion-upgrade-main              | [PR: 32961](https://github.com/kubernetes/test-infra/pull/32961)| [PR: 33037](https://github.com/kubernetes/test-infra/pull/33037) Running on `eks-prow-build-cluster` |
| periodic-cluster-api-provider-azure-e2e-main                             | [PR: 32961](https://github.com/kubernetes/test-infra/pull/32961)|[PR: 33037](https://github.com/kubernetes/test-infra/pull/33037) Running on `eks-prow-build-cluster` |
| periodic-cluster-api-provider-azure-e2e-aks-main                         | [PR: 32961](https://github.com/kubernetes/test-infra/pull/32961)| https://github.com/kubernetes/test-infra/pull/33013 Running at `k8s-infra-prow-build` |
|periodic-cluster-api-provider-azure-coverage| Does not use WI creds | running on `k8s-infra-prow-build`|

- [x] [cluster-api-provider-azure-periodics-main-upgrades.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-azure/cluster-api-provider-azure-periodics-main-upgrades.yaml)

| Test Job Name                                                          |Migrate to use Workload Identity                                                        | Moved to community cluster |
|------------------------------------------------------------------------|---------------------------------------------------------------|---------------|
| periodic-cluster-api-provider-azure-e2e-workload-upgrade-1-26-1-27-main| [PR: 32963](https://github.com/kubernetes/test-infra/pull/32963) | https://github.com/kubernetes/test-infra/pull/33027 working on `eks-prow-build-cluster` |
| periodic-cluster-api-provider-azure-e2e-workload-upgrade-1-27-1-28-main| [PR: 32963](https://github.com/kubernetes/test-infra/pull/32963) | https://github.com/kubernetes/test-infra/pull/33027 working on `eks-prow-build-cluster` |
| periodic-cluster-api-provider-azure-e2e-workload-upgrade-1-28-1-29-main| [PR: 32963](https://github.com/kubernetes/test-infra/pull/32963) | [PR: 33037](https://github.com/kubernetes/test-infra/pull/33037) Running on `eks-prow-build-cluster` |

- [x] [cluster-api-provider-azure-periodics-v1beta1-release-1.15.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-azure/cluster-api-provider-azure-periodics-v1beta1-release-1.15.yaml)

| Test Job Name                                                          | Migrate to use Workload Identity | Moved to community cluster |
|------------------------------------------------------------------------|---------|---------|
| periodic-cluster-api-provider-azure-capi-e2e-v1beta1-release-1-15      |   https://github.com/kubernetes/test-infra/pull/32964      | https://github.com/kubernetes/test-infra/pull/32964  working on `eks-prow-build-cluster` |
| periodic-cluster-api-provider-azure-e2e-v1beta1-release-1-15          |    https://github.com/kubernetes/test-infra/pull/32964     | https://github.com/kubernetes/test-infra/pull/32964  working on `eks-prow-build-cluster` |
| periodic-cluster-api-provider-azure-e2e-aks-v1beta1-release-1-15       |   https://github.com/kubernetes/test-infra/pull/32964     |  https://github.com/kubernetes/test-infra/pull/32964  working on `eks-prow-build-cluster`|

- [x] [cluster-api-provider-azure-periodics-v1beta1-release-1.16.yaml](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-azure/cluster-api-provider-azure-periodics-v1beta1-release-1.16.yaml)

| Test Job Name                                                                 | Migrate to use Workload Identity |Moved to community cluster |
|-------------------------------------------------------------------------------|---------|---------|
| periodic-cluster-api-provider-azure-conformance-v1beta1-release-1-16          |   https://github.com/kubernetes/test-infra/pull/32965      | https://github.com/kubernetes/test-infra/pull/32965 running on `eks-prow-build-cluster` |
| periodic-cluster-api-provider-azure-conformance-v1beta1-with-ci-artifacts-release-1-16 |   https://github.com/kubernetes/test-infra/pull/32965      |https://github.com/kubernetes/test-infra/pull/32965 running on `eks-prow-build-cluster` |
| periodic-cluster-api-provider-azure-capi-e2e-v1beta1-release-1-16             |     https://github.com/kubernetes/test-infra/pull/32965    | https://github.com/kubernetes/test-infra/pull/32965 running on `eks-prow-build-cluster` |
| periodic-cluster-api-provider-azure-e2e-v1beta1-release-1-16                 |    https://github.com/kubernetes/test-infra/pull/32965     |https://github.com/kubernetes/test-infra/pull/32965 running on `eks-prow-build-cluster`  |
| periodic-cluster-api-provider-azure-e2e-aks-v1beta1-release-1-16              |     https://github.com/kubernetes/test-infra/pull/32965    | https://github.com/kubernetes/test-infra/pull/32965 running on `eks-prow-build-cluster` |

```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4980
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4939
- [ ] https://github.com/kubernetes/test-infra/pull/32942
- [ ] https://github.com/kubernetes/test-infra/pull/32955
- [ ] https://github.com/kubernetes/test-infra/pull/32956
- [ ] https://github.com/kubernetes/test-infra/pull/32960
- [ ] https://github.com/kubernetes/test-infra/pull/32961
- [ ] https://github.com/kubernetes/test-infra/pull/32963
- [ ] https://github.com/kubernetes/test-infra/pull/32964
- [ ] https://github.com/kubernetes/test-infra/pull/32965
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4977
- [ ] https://github.com/kubernetes/test-infra/pull/32974
- [ ] https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4998
- [ ] https://github.com/kubernetes/test-infra/pull/33013
- [ ] https://github.com/kubernetes/test-infra/pull/33027
- [ ] https://github.com/kubernetes/test-infra/pull/33029
- [ ] https://github.com/kubernetes/test-infra/pull/33030
- [ ] https://github.com/kubernetes/test-infra/pull/33052
```

**Comment by jsturtevant** [comment]
We will want to migrate all of the periodic as well, but this should be easier once pull requests are validated as they are similar code paths.

Once we've migrated to WI, we should be ready to transition to community cluster

**Comment by dtzar** [comment]
Closing this since all the CAPZ issues have been completed.  If there issues or questions with others who depend on CAPZ, please feel free to file an issue, ping us on Slack, or come to the community call.
