### ISSUE TITLE
Fix mgmt - workload cluster communication timeout issue

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api-provider-azure#5261]
New SFI policies are blocking Management cluster's resources from accessing workload cluster's API Server. 
This is mostly happening because the workload cluster's API server is not accessible from the internet. 

One of the solutions is to 

```[tasklist]
### Tasks
- [x] Ensure that the management cluster and the workload cluster created do not have overlapping CIDRs.
- [x] Peer the VNets of the management cluster.
- [x] Create a private DNS Zone between them and manually create a record resolving the `<Azure_location>.cloudapp.com` with the internal IP of the workload cluster.
- [x] Delete all the peerings from the management cluster Vnet every time the delete all workload clusters is clicked in Tilt.
```
