### ISSUE TITLE
Make internal LB IP configurable

### ISSUE THREAD

**Issue by nawazkh** [kubernetes-sigs/cluster-api-provider-azure#5264]
CAPZ assigns a default IP of `10.0.0.100` to the internal Load Balancer. We would like to make this configurable by the user. 
Also add validation to the webhooks validating _newly configured Internal LB IP_ belongs to the Control plane Subnet CIDR.
```[tasklist]
### Tasks
- [x] Create an optional job at K8s-test-infra to test APIServer ILB changes.
- [x] Create an e2e test at runs the new APIServerILB templates
- [x] Create APIServerILB tempalates for prow/ci
```

**Comment by nawazkh** [comment]
Unable to make progress on https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5248 unless the internal lb IP is configurable
