### ISSUE TITLE
[Umbrella] capz MVP - Known Issues

### ISSUE THREAD

**Issue by justaugustus** [kubernetes-sigs/cluster-api-provider-azure#92]
As we move through a few refactoring efforts (https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/68, https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/88), it's a good time to capture some of the work required to bring us to a MVP capz implementation.

Here are some known issues that we'd want to resolve for the mvp:
- [x] (#100) `master` builds (i.e., `make binaries-dev` works), but doesn't result in a working cluster
- [x] (#97) Repo versioning
- [x] (#98) Document development process
- [x] (#101) capz needs to be deployed in a region that supports Availability Zones
  - [x] Resources (VM + NIC public IP) are hard-coded to Zone 3
- [x] (#102) VM cannot be attached to backend pool (NIC needs to either use a Standard SKU PIP or not have a PIP attached) & backend pool reconciliation code doesn't exist
- [x] (#103) Store public IP DNS name in Cluster object for use in machine scripts (includes updating associated types)
- [ ] (#104) Control plane VM is open to the internet
- [x] (#105) Subnets + NSGs: ReconcileNetwork should implement two subnets, control plane and node, with NSGs scoped to the role
- [x] (#106) Implement/update delete methods for Cluster/Machine objects

Additional things to consider, but are not strictly required for mvp:
- [x] (#107) Investigating using distroless/static for image building (https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/88/files#r259902819)
- [x] (#108) Update Makefile
- [x] (#109) Types need to be updated (+ regenerate deepcopy, CRDs, RBAC)
- [ ] (#110) Minimize calls to Azure by storing more information in Cluster & Machine objects
- [x] (#111) Update helper packages (tokens, certificates, etc.)
- [ ] (#112) Dedupe dependencies and move startup scripts to cloud-init
- [ ] (#113) Investigate VMSS (Virtual Machine Scale Sets)
- [x] (#114) Hard-coded parameters
- [ ] (#94) Improve logging
- [x] (#115) More intelligent reconcile logic for subresources

I'll get these into their own issues; just wanted to open this umbrella as a starting point.

/milestone mvp
/cc @soggiest @tariq1890

**Comment by justaugustus** [comment]
I think we've done a good job of taking care of most of the MVP items and I've re-prioritized the remaining issues on this umbrella.
/close
